#!/bin/sh

# Xcode Cloud post-clone hook.
#
# Schrift's `Schrift.xcodeproj` is generated by XcodeGen from `project.yml` and
# is intentionally NOT committed (it is git-ignored — see `.gitignore`). Xcode
# Cloud clones the GitHub repository verbatim, so without this hook the build
# fails immediately with:
#
#     Project Schrift.xcodeproj does not exist at the root of the repository
#
# Xcode Cloud runs this script right after cloning and before it resolves
# dependencies or invokes xcodebuild, so regenerating the project here makes it
# available for the rest of the build — mirroring the `xcodegen generate` step
# the fastlane / GitHub Actions pipeline runs (see fastlane/Fastfile and
# .github/workflows/testflight.yml).

set -euo pipefail

# Xcode Cloud runs ci_scripts/* with the working directory set to ci_scripts.
# Prefer Apple's documented path to the primary repository checkout, but fall
# back to this script's parent directory (ci_scripts always lives at the repo
# root) so we don't depend on the exact env-var name Apple happens to expose.
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"

echo "Installing XcodeGen via Homebrew…"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
brew install xcodegen

echo "Generating Schrift.xcodeproj from project.yml…"
cd "$REPO_ROOT"
xcodegen generate

echo "Generated $REPO_ROOT/Schrift.xcodeproj"
